### ISSUE TITLE
Select command silently failed with columns designation or return a truncated dump

### ISSUE THREAD

**Issue by BcApi6L** [MarkPflug/Sylvan.Tools.Etl#4]
Hello,
It is first time for me to fill an issue report on Github so I'll try my best to point you the right direction...
I tried your very seducing tool to hopefuly solve a data collect problem I met for my job in an elegant way (I believe).

Steps to reproduce:
1. Installing trough dotnet tool (6.0.402) as asked in readme.md (Win.10, PwSh 5.1&7.2.6, Windows Terminal)
2. In the same directory : 
- Analyse a file.csv (48 lines, mostly rfc4180 respectful, headers defined, us-acsii, has empty cols) (see example file attached)
--> OK, file.csv.schema is created with a minor error recognizing datetime column (supposedly because french locales).
- Import to Sqlite 
--> OK, Db file is created and quering works fine despite a bit strange behavior in columns naming (column name become "NameConstraintConstraint" (this is minor error)
- Select from file.csv (setl select example.csv dump.csv 0 1 2)
--> Fails in any case with columns parameter set but works partially when using empty column parameter (returned dump file is truncated after character number 4022).

Please, feel free to ask any information you need.
I do really want to integrate your tool in our ETL script toolbox but i'm a bit feared to use it as-is :)

Thanks by advance

[example.csv](https://github.com/MarkPflug/Sylvan.Tools.Etl/files/9930070/example.csv)

**Comment by MarkPflug** [comment]
Date's aren't being detected, because the data appears... wrong. The very first line of data contains `03/21/2022 15:93:23`. I don't know anything about French culture, but "93" looks incorrect to me.

Sqlite name change, I'd need a concrete example of what you're seeing.

Select might have been broken in v0.1.1. I just pushed 0.1.2, which might fix it. Let me know if you're still seeing this behavior after updating.

**Comment by BcApi6L** [comment]
Oh yes... You are absolutly right!
We definitly also have 60 seconds by minute... :D
I'm so sorry... my mistake when creating sample csv file

Anyway this doesn't seems to bother none of the involved components :

```
`PS C:\temp> C:\bin\sqlite\sqlite3.exe .\ex.db "SELECT * FROM example WHERE Liwivtextinteger = 25"
25|0|25|X|0||68|||||||L||H1d8009|\\zw1\wuh31\K\F\ZKKORWZGZ\XP\tivhszn\QRIVUVMG|03/21/2022 15:87:09`
```

For columns naming problem. I missed that one but constraints seems poorly applied to Sqlite...
Please pay attention to "WzgvUrxsrvi" which in my sample should be DateTime (Numeric) column.

```
> PS C:\temp> C:\bin\sqlite\sqlite3.exe .\ex.db "PRAGMA table_info(example)"
> 0|Liwivtextinteger||0||0
> 1|Kvirlwvtextinteger||0||0
> 2|Wfivvtextinteger||0||0
-- (cut) --
> 16|MlnUrxsrvitexttext||0||0
> 17|WzgvUrxsrvitexttext||0||0
```

Database "ex.db" was issued from this schema :
(even with correct dates DateTime will never been recognized)

```
> PS C:\temp> gc .\example.csv.schema
> Liwiv:int,
> Kvirlwv:Boolean?{|n},
> Wfivv:int?,
> GbkvXlkrv:String?,
> Lirtrmv:Boolean?{|f},
> Krelg:String?,
> Xlmgilov:int?,
> Zkkligvfi1:String?,
> Zkkligvfi2:String?,
> Mvgglbztv:String?,
> Rmul1,
> Rmul2:String?,
> Wlfyov:String?,
> Hfkkivhhrlm:String?,
> Kzbh:String?,
> Hvievfi,
> MlnUrxsrvi,
> WzgvUrxsrvi
```

I'll try 0.1.2 just now and will tell you what's new/different.
Also sorry for random names in sample data... I now realizer that's a bit hard to read
Let me know if you want another sample set with preferably more readable texts inside ?

Again, thank you for your help

**Comment by BcApi6L** [comment]
Tried version 0.1.2... and so far so good... no more select problem and columns name's are ok... That's great!
Thank you very much
